// Standalone entry point for mavlink_bridge_node.
//
// Hand-written rather than generated by rclcpp_components_register_node, because the
// generated main spins a SingleThreadedExecutor. The bridge blocks on MAVROS service calls
// from inside its own service callbacks, so a single-threaded executor would deadlock and
// every arm request would time out.

#include <memory>

#include <rclcpp/rclcpp.hpp>

#include "j10_mavlink/mavlink_bridge_node.hpp"

int main(int argc, char ** argv)
{
  rclcpp::init(argc, argv);

  rclcpp::NodeOptions options;
  auto node = std::make_shared<j10_mavlink::MavlinkBridgeNode>(options);

  // Five threads, one per mutually-exclusive callback group: setpoint timer,
  // subscriptions, service servers, takeoff, service clients. Takeoff has its own group
  // because it blocks for the duration of the climb and must not hold up disarm.
  rclcpp::executors::MultiThreadedExecutor executor(rclcpp::ExecutorOptions(), 5);
  executor.add_node(node);
  executor.spin();

  rclcpp::shutdown();
  return 0;
}
